/**
 * Windmill server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.38.0
 * Contact: contact@windmill.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BranchOneBranches } from './BranchOneBranches.ts';
import { FlowModule } from './FlowModule.ts';
import { HttpFile } from '../http/http.ts';

export class BranchOne {
    'branches': Array<BranchOneBranches>;
    '_default': Array<FlowModule>;
    'type': BranchOneTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "branches",
            "baseName": "branches",
            "type": "Array<BranchOneBranches>",
            "format": ""
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "Array<FlowModule>",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "BranchOneTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BranchOne.attributeTypeMap;
    }

    public constructor() {
    }
}


export type BranchOneTypeEnum = "branchone" ;

