/**
 * Windmill server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.38.1
 * Contact: contact@windmill.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FlowModule } from './FlowModule.ts';
import { HttpFile } from '../http/http.ts';

export class BranchOneBranches {
    'summary'?: string;
    'expr': string;
    'modules': Array<FlowModule>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "expr",
            "baseName": "expr",
            "type": "string",
            "format": ""
        },
        {
            "name": "modules",
            "baseName": "modules",
            "type": "Array<FlowModule>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BranchOneBranches.attributeTypeMap;
    }

    public constructor() {
    }
}

