/**
 * Windmill server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.36.0
 * Contact: contact@windmill.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FlowValueRetryConstant } from './FlowValueRetryConstant.ts';
import { FlowValueRetryExponential } from './FlowValueRetryExponential.ts';
import { HttpFile } from '../http/http.ts';

export class FlowValueRetry {
    'constant'?: FlowValueRetryConstant;
    'exponential'?: FlowValueRetryExponential;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "constant",
            "baseName": "constant",
            "type": "FlowValueRetryConstant",
            "format": ""
        },
        {
            "name": "exponential",
            "baseName": "exponential",
            "type": "FlowValueRetryExponential",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FlowValueRetry.attributeTypeMap;
    }

    public constructor() {
    }
}

