/**
 * Windmill server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.38.0
 * Contact: contact@windmill.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class InlineResponse2002Asks {
    'id': number;
    'askId': number;
    'summary': string;
    'app': string;
    'approved': boolean;
    'kind': InlineResponse2002AsksKindEnum;
    'votes': number;
    'views': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "askId",
            "baseName": "ask_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "app",
            "baseName": "app",
            "type": "string",
            "format": ""
        },
        {
            "name": "approved",
            "baseName": "approved",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "InlineResponse2002AsksKindEnum",
            "format": ""
        },
        {
            "name": "votes",
            "baseName": "votes",
            "type": "number",
            "format": ""
        },
        {
            "name": "views",
            "baseName": "views",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2002Asks.attributeTypeMap;
    }

    public constructor() {
    }
}


export type InlineResponse2002AsksKindEnum = "script" | "failure" | "trigger" | "command" ;

