/**
 * Windmill server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.38.0
 * Contact: contact@windmill.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JavascriptTransform } from './JavascriptTransform.ts';
import { StaticTransform } from './StaticTransform.ts';
import { HttpFile } from '../http/http.ts';

export class InputTransform {
    'value'?: any;
    'type': InputTransformTypeEnum;
    'expr': string;

    static readonly discriminator: string | undefined = "type";

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "any",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "InputTransformTypeEnum",
            "format": ""
        },
        {
            "name": "expr",
            "baseName": "expr",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InputTransform.attributeTypeMap;
    }

    public constructor() {
        this.type = "InputTransform";
    }
}


export type InputTransformTypeEnum = "javascript" ;

