/**
 * Windmill server API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.32.0
 * Contact: contact@windmill.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class JavascriptTransform {
    'expr': string;
    'type': JavascriptTransformTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "expr",
            "baseName": "expr",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "JavascriptTransformTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JavascriptTransform.attributeTypeMap;
    }

    public constructor() {
    }
}


export type JavascriptTransformTypeEnum = "javascript" ;

